---
- name: Update system repository source
  hosts: all
  become: true
  roles:
    - role: update_repo

- name: Update system packages
  hosts: all
  become: true
  roles:
    - role: update_system

- name: Setup packages
  hosts: all
  become: true
  roles:
    - role: setup_packages

- name: Configure system configs
  hosts: all
  become: true
  roles:
    - role: configure_system

- name: Setup LVM Thin volumes on PVE
  hosts: pve_node
  become: true
  vars_files:
    - secrets.yaml
  roles:
    - role: setup_lvm_thin

- name: Configure IP Address
  hosts: pve_node
  become: true
  vars_files:
    - vars.yaml
  roles:
    - role: pve_ip

- name: Configure DNS Settings on PVE
  hosts: pve_node
  become: true
  vars_files:
    - vars.yaml
  roles:
    - role: pve_dns

- name: Configure PVE Cluster
  hosts: pve_node
  become: true
  vars_files:
    - vars.yaml
    - secrets.yaml
  roles:
    - role: pve_cluster

- name: Configure PVE Storage
  hosts: pve_node
  become: true
  roles:
    - role: pve_storage

- name: Configure PVE ACME
  hosts: pve_node
  become: true
  vars_files:
    - vars.yaml
    - secrets.yaml
  roles:
    - role: pve_acme

- name: Configure NUT
  hosts: all
  become: true
  vars_files:
    - secrets.yaml
  roles:
    - role: nut

- name: Configure Vector
  hosts: all
  become: true
  roles:
    - role: vector