---
- name: Install TPM2 userspace tools
  ansible.builtin.package:
    name:
      - tpm2-tools
    state: present

- name: Nuke NVMe drive
  ansible.builtin.command: wipefs -a /dev/nvme0n1

- name: Init drive with GPT label
  community.general.parted:
    device: /dev/nvme0n1
    label: gpt
    number: 1
    flags: [ lvm ]
    part_start: 0%
    part_end: 100GiB
    state: present

- name: Nuke partition internal LUKS header
  ansible.builtin.command: wipefs -a /dev/nvme0n1p1

- name: Create LUKS container with host password
  community.crypto.luks_device:
    device: /dev/nvme0n1p1
    passphrase: "{{ luks_passwords[inventory_hostname] }}"
    state: present
  no_log: true

- name: Enroll TPM2 keyslot via systemd-cryptenroll (PCR 0+7)
  ansible.builtin.command: >
    systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0+7 /dev/nvme0n1p1
  environment:
    PASSWORD: "{{ luks_passwords[inventory_hostname] }}"
  no_log: true

- name: Configure crypttab for automatic TPM2 unlock
  community.general.crypttab:
    name: crypt_nvme
    backing_device: /dev/nvme0n1p1
    password: none
    opts: discard,tpm2-device=auto
    state: present
  no_log: true

- name: Open LUKS container
  community.crypto.luks_device:
    device: /dev/nvme0n1p1
    name: crypt_nvme
    passphrase: "{{ luks_passwords[inventory_hostname] }}"
    allow_discards: true
    state: opened

- name: Create LVM Physical Volume on LUKS device
  community.general.lvm_pv:
    device: /dev/mapper/crypt_nvme
    state: present

- name: Create LVM Volume Group
  community.general.lvg:
    vg: vg_nvme
    pvs: /dev/mapper/crypt_nvme
    state: present

- name: Create LVM Thin Pool
  community.general.lvol:
    vg: vg_nvme
    thinpool: "nvme-lvm-thin"
    size: 100%FREE
    state: present