pollinterval = 1

[VX-600VA]
  driver = nutdrv_qx
  product = "USB to Serial"
  desc = "Delta VX-600VA UPS"
  port = auto
  vendorid = 0665
  productid = 5161
  vendor = "INNO TECH"
  bus = 001
  override.battery.charge.low = 50