---
- name: Create VM
  hosts: all
  become: true
  vars_files:
    - vars.yaml
  roles:
    - role: create_vm

- name: Start VM
  hosts: all
  become: true
  vars_files:
    - vars.yaml
  roles:
    - role: start_vm