---
- name: Update mirror (Rocky Linux)
  ansible.builtin.include_tasks: rocky.yaml
  when: "'file_node' in group_names"

- name: Update mirror (Proxmox VE)
  ansible.builtin.include_tasks: pve.yaml
  when: "'pve_node' in group_names"

- name: Update mirror (Pi)
  ansible.builtin.include_tasks: pi.yaml
  when: "'pi_node' in group_names"