---
- name: Update Raspberry Pi Debian mirror
  ansible.builtin.shell: |
    sed -i.bak \
      -e 's|http://deb.debian.org/debian/|https://mirror.techlabs.co.kr/debian|g' \
      -e 's|http://deb.debian.org/debian-security/|https://mirror.techlabs.co.kr/debian-security|g' \
      /etc/apt/sources.list.d/debian.sources