- name: Set Avahi package name
  ansible.builtin.set_fact:
    avahi_package_name: "{{ 'avahi' if ansible_facts['os_family'] == 'RedHat' else 'avahi-daemon' }}"
    mdns_pkg: "{{ 'nss-mdns' if ansible_facts['os_family'] == 'RedHat' else 'libnss-mdns' }}"

- name: Install Avahi and nss-mdns package
  ansible.builtin.package:
    name:
      - "{{ avahi_package_name }}"
      - "{{ mdns_pkg }}"
    state: present

- name: Enable and start Avahi daemon
  ansible.builtin.service:
    name: avahi-daemon
    enabled: true
    state: started