- name: Install Chrony package
  ansible.builtin.package:
    name: chrony
    state: present

- name: Disable systemd-timesyncd service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: stopped
    enabled: false
  failed_when: false

- name: Copy Chrony configuration file
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "{{ '/etc/chrony/chrony.conf' if ansible_facts['os_family'] == 'Debian' else '/etc/chrony.conf' }}"
    owner: root
    group: root
    mode: '0644'

- name: Ensure Chrony service is running and enabled
  ansible.builtin.systemd:
    name: "{{ 'chrony' if ansible_facts['os_family'] == 'Debian' else 'chronyd' }}"
    state: started
    enabled: true

- name: Restart Chrony Service
  ansible.builtin.systemd:
    name: "{{ 'chrony' if ansible_facts['os_family'] == 'Debian' else 'chronyd' }}"
    state: restarted