---
- name: Configure SSH Security settings via Jinja2 template
  ansible.builtin.template:
    src: 99-security.conf.j2
    dest: /etc/ssh/sshd_config.d/99-security.conf
    owner: root
    group: root
    mode: '0644'
    validate: /usr/sbin/sshd -t -f %s

- name: Restart SSH Service
  ansible.builtin.systemd:
    name: "{{ 'ssh' if ansible_facts['os_family'] == 'Debian' else 'sshd' }}"
    state: restarted